Restore OCaml auto-configure step with an opt-out

diff --git a/dist/gcc-compatible/configure b/dist/gcc-compatible/configure
--- a/dist/gcc-compatible/configure
+++ b/dist/gcc-compatible/configure
@@ -35,6 +35,34 @@ my_mktemp_c () {
 # Helpers to help do feature or bug detection
 # -------------------------------------------
 
+detect_ocamlfind () {
+  package=$1
+  loc=$(ocamlfind query $package)
+  r=$?
+  if [[ $r == 0 ]]; then
+    echo "... found $package in $loc"
+  else
+    echo "OCaml package $package not found"
+  fi
+  return $r
+}
+
+detect_ocaml () {
+  # Detect ocamlfind
+  loc=$(which ocamlfind)
+  r=$?
+  if [[ $r == 0 ]]; then
+    echo "... found ocamlfind in $loc"
+  else
+    echo "ocamlfind not found"
+    return 1
+  fi
+  # Detect packages
+  for p in ctypes ctypes.foreign; do
+    detect_ocamlfind $p || return 1
+  done
+}
+
 check_no_bug81300 () {
   if [[ "$cross_build" == "1" ]]; then
     # We don't want to build anything with march=native
@@ -199,8 +227,9 @@ show_help () {
   printf "                    * aarch64-apple-ios\n"
   printf "                    * x86_64-apple-ios-simulator\n"
   printf "    --disable-bzero Do not use explicit_bzero (binary will work with an old GLIBC)\n"
-  printf "    --disable-ocaml Disable OCAML bindings\n"
   printf "    --enable-power9 Enable Power ISA v3.0 instruction set for PowerPC architecture\n"
+  printf "    --disable-ocaml Always disable OCAML bindings\n"
+  printf "    --enable-ocaml  Always enable OCAML bindings\n"
   printf "\n"
 }
 
@@ -210,6 +239,7 @@ echo -n > Makefile.config
 echo -n > config.h
 
 # Default arguments
+enable_ocaml=0
 disable_ocaml=0
 disable_bzero=0
 enable_power9=0
@@ -220,6 +250,7 @@ all_args=("$@")
 while [ $# -gt 0 ]; do
     case "$1" in
         -target) build_target="$2"; shift ;;
+        --enable-ocaml) enable_ocaml=1 ;;
         --disable-ocaml) disable_ocaml=1 ;;
         --disable-bzero) disable_bzero=1 ;;
         --enable-power9) enable_power9=1 ;;
@@ -475,7 +506,7 @@ if ! detect_uint128; then
   echo "CFLAGS += -DKRML_VERIFIED_UINT128" >> Makefile.config
 fi
 
-if [[ "$disable_ocaml" == "1" ]]; then
+if [[ "$enable_ocaml" == "0" ]] || [[ "$disable_ocaml" == "1" ]] || ! detect_ocaml; then
   echo "OCaml bindings disabled"
   echo "DISABLE_OCAML_BINDINGS=1" >> Makefile.config
 fi
